### ISSUE TITLE
 useGameEventProvider does not emit any data

### ISSUE THREAD

**Issue by Simple-MAX** [AlbericoD/overwolf-hooks#3]
**Describe the bug**
While the targeted game running rebuilding the react app causes some issues. the useGameEventProvider does not emit any data

**To Reproduce**
1. change any file and save
3. rebuild
4. info and event will be undefined

**Expected behavior**
get info and event that are emitted by OW from useGameEventProvider

**Screenshots**
![image](https://user-images.githubusercontent.com/19856805/115980130-993e5100-a58a-11eb-9dfb-314fa35c2f7d.png)
![image](https://user-images.githubusercontent.com/19856805/115980145-ad824e00-a58a-11eb-9193-6b40886c36c6.png)

**Comment by mocca-dev** [comment]
Hey @Simple-MAX!! have you had any progress with this? I am in the same situation and I can't do anything to continue with the development of my app

**Comment by Simple-MAX** [comment]
@mocca-dev yes I posted on Overwolf developer discord

**Comment by mocca-dev** [comment]
ah ok! I already did a research but I couldn't find you in the Overwolf discord. Have you use the same nickname?
